function main() {
    var file = File.open("test1.txt", "w");
    file.write("Operators test:\n")
    startApplication("Calculator");
    clickButton(waitForObject(":MainWindow.pushButton_1_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_5_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_square_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_equals_QPushButton"));
    test.compare(waitForObjectExists(":MainWindow.lineEdit_QLineEdit").text, "3.87298");
    clickButton(waitForObject(":MainWindow.pushButton_clear_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_1_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_add_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_9_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_equals_QPushButton"));
    test.compare(waitForObjectExists(":MainWindow.lineEdit_QLineEdit").text, "10");
    clickButton(waitForObject(":MainWindow.pushButton_clear_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_1_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_5_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_8_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_substract_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_5_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_2_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_6_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_equals_QPushButton"));
    test.compare(waitForObjectExists(":MainWindow.lineEdit_QLineEdit").text, "-368");
    clickButton(waitForObject(":MainWindow.pushButton_clear_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_4_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_5_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_6_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_multiply_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_pi_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_equals_QPushButton"));
    test.compare(waitForObjectExists(":MainWindow.lineEdit_QLineEdit").text, "1432.56625003694");
    clickButton(waitForObject(":MainWindow.pushButton_clear_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_1_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_5_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_4_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_multiply_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_exp_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_equals_QPushButton"));
    test.compare(waitForObjectExists(":MainWindow.lineEdit_QLineEdit").text, "418.615401582694");
    clickButton(waitForObject(":MainWindow.pushButton_clear_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_1_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_2_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_3_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_4_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_5_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_6_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_7_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_8_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_9_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_27_QPushButton"));
    test.compare(waitForObjectExists(":MainWindow.lineEdit_QLineEdit").text, "12345678");
    clickButton(waitForObject(":MainWindow.pushButton_clear_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_1_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_5_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_8_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_divide_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_2_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_point_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_5_QPushButton"));
    clickButton(waitForObject(":MainWindow.pushButton_equals_QPushButton"));
    test.compare(waitForObjectExists(":MainWindow.lineEdit_QLineEdit").text, "63.2");
    file.write("\tPass:" + String(test.resultCount("passes"))
        + "\n\tFail:" + String(test.resultCount("fails")));
    file.close();
}
